### ISSUE TITLE
Voidmetal Chisel

### ISSUE THREAD

**Issue by soundlogic2236** [TehNut/MoreChisels#10]
The voidmetal chisel neither repairs nor warps. It doesn't really seem to be voidmetal at all.

**Comment by TehNut** [comment]
Did you _have_ to make separate issues for these?

**Comment by soundlogic2236** [comment]
Sorry. I wasn't aware that would be a problem.

**Comment by TehNut** [comment]
Fixed in ddf6c86a45f7daadce5eb47bea385a7591a7e8a5
