### ISSUE TITLE
Extra Utilities Chisel problems.

### ISSUE THREAD

**Issue by PaperTriangle** [TehNut/MoreChisels#12]
While having Bedrockium Ingots disabled in Extra Utilities, More Chisels still tries to register the recipe on a null item, causing the game to crash at start-up because of "java.lang.RuntimeException: Invalid shaped ore recipe:  I, U , U, ingotUnstable, I, null, 1xitem.morechisels.chisel.bedrockium@0 "
This still occurs if the More Chisels config option for Bedrockium Chisels is off.

And then, leaving Bedrockium Ingots enabled, but disabling the Bedrockium Chisel results in a crafting recipe to crash the game:
![2015-03-02_02 46 57](https://cloud.githubusercontent.com/assets/10346216/6431571/92ffc33a-c087-11e4-8b95-84d9a2d87c00.png)

**Comment by TehNut** [comment]
Heh... When I switched some recipes to "Themed" recipes I stopped using my custom registry that checks for the item being null first.
