### ISSUE TITLE
Fluxed Chisel instantly breaks when used in an auto-chisel

### ISSUE THREAD

**Issue by Sovereignty89** [TehNut/MoreChisels#2]
Fluxed Chisel, at any charge, fully or anything else, instantly breaks when used in an auto-chisel.
Your other chisels (I couldn't check the bound one since I have no understanding of BM) do not seem to have this problem.

**Comment by TehNut** [comment]
Known. Fixed locally but it completely broke auto-chisel usage. I'm working with tterrag to fix it.

**Comment by TehNut** [comment]
This got fixed at some point
