### ISSUE TITLE
Add compatibility for ChiselTeam fork

### ISSUE THREAD

**Issue by Hjaldar** [TehNut/MoreChisels#25]
Please consider adding compatibility for the new Chisel fork, similarly to what you did for ChiselTones.

When I attempt to run the new Chisel fork and More Chisels I get the error "java.lang.NoClassDefFoundError: com/cricketcraft/chisel/item/chisel/ItemChisel".

Thanks

**Comment by TehNut** [comment]
I already have this fixed on my end, I just want to ~~hammer~~ chisel out some details first.

**Comment by Hjaldar** [comment]
Great. Thank you.

**Comment by spannerman79** [comment]
This might still be an issue - I just grabbed build [43](http://coloredlightscore.us.to:8080/job/Chisel-2%20v1.7.10/43/artifact/build/libs/Chisel2-2.5.0.43.jar) (issue #26 )  from your jenkins and I got the ~~same~~ similar error as this issue title.

Crash Log: http://paste.ee/p/fg9DE

In short;

```
cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: team/chisel/item/chisel/ItemChisel
```

Currently no issues with [MoreChisels - 1.0-20](http://minecraft.curseforge.com/mc-mods/227904-morechisels/files/2230667) though.

**Comment by TehNut** [comment]
alsdjflasdfjlasf

**Comment by TehNut** [comment]
@spannerman79 

hey you i just noticed you're not on the ChiselTeam fork. That's all the new builds support.

**Comment by spannerman79** [comment]
Off which branch @TehNut ?
[This](http://coloredlightscore.us.to:8080/job/Chisel-2%20v1.7.10/) one or the DEV branch being [this](http://coloredlightscore.us.to:8080/job/Chisel-2%20v1.7.10-Dev/)

If its the first one then yes - I am already using that particual mod ( [this](http://coloredlightscore.us.to:8080/job/Chisel-2%20v1.7.10/43/artifact/build/libs/Chisel2-2.5.0.43.jar)  one to be exact)

Edit:  The MD5 hash via http://coloredlightscore.us.to:8080/job/Chisel-2%20v1.7.10/43/artifact/build/libs/Chisel2-2.5.0.43.jar is identical from curse forge http://minecraft.curseforge.com/mc-mods/225236-chisel-2/files/2253599

![chisel2](https://cloud.githubusercontent.com/assets/7542384/9562117/c3033696-4ea5-11e5-83d8-3168e1e2f2ff.PNG)

**Comment by TehNut** [comment]
The ChiselTeam fork is [here](http://minecraft.curseforge.com/mc-mods/235279-chisel).

**Comment by lilmoefow** [comment]
Didnt want to open a new issues just to say this.  With the update it doesnt seem to add the Fluxed Chisel any more.  Im not using Thermal expansion but i have Redstone Arsenal and Ender IO and i have the configs set to register those recipes. No sure why it isnt workin.

Using: 

forge-10.13.4.1448.jar

Chisel-2.9.0.3.jar
CoFHCore-[1.7.10]3.0.4B1-308.jar
EnderCore-1.7.10-0.1.0.19_beta.jar
EnderIO-1.7.10-2.3.0.408_beta.jar
MoreChisels-1.7.10-1.0-25.jar
RedstoneArsenal-[1.7.10]1.1.1-89.jar

```
# Requires EnderIO to be present.
B:addEnderIOFluxedChiselRecipes=true

# Requires RedstoneArsenal to be present.
B:addRedstoneArsenalFluxedChiselRecipes=true

# Requires ThermalExpansion to be present.
B:addThermalExpansionFluxedChiselRecipes=false
```

**Comment by Shahelion** [comment]
Doesn't Redstone Arsenal require Thermal Expansion?

**Comment by TehNut** [comment]
No..? Never has. Also forgot to close this.
