### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by Tsyklop** [TehNut/MoreChisels#27]
Crash: http://pastebin.com/qHh7FSea

MoreChisels-1.7.10-1.0-24, Chisel2-2.5.0.43, extrautilities-1.2.11

**Comment by spannerman79** [comment]
https://github.com/TehNut/MoreChisels/issues/25#issuecomment-135926363

**Comment by TehNut** [comment]
Update to ChiselTeam version.

**Comment by Tsyklop** [comment]
@TehNut Chisel 2 laset version

http://minecraft.curseforge.com/mc-mods/225236-chisel-2/files/2253599

**Comment by TehNut** [comment]
@Tsyklop That's Cricket's fork. ChiselTeam's is [here](http://minecraft.curseforge.com/mc-mods/235279-chisel).

**Comment by Tsyklop** [comment]
@TehNut What's the difference between them?

**Comment by TehNut** [comment]
One is being updated, one isn't.

**Comment by Tsyklop** [comment]
@TehNut Thx. ChiselTeam version all OK

**Comment by spannerman79** [comment]
~~@TehNut please update your [project](http://minecraft.curseforge.com/mc-mods/227904-morechisels) to link to the correct Chisel 2 mod - as I am sure I would not be the only one that would be confused on this matter.~~

Nevermind - idiot me didn't read properly
