### ISSUE TITLE
Gem Chisels are not translatable

### ISSUE THREAD

**Issue by labpaw** [TehNut/MoreChisels#7]
There are only "item.morechisels.chisel.gem.name=%s Chisel" line in .lang file but the actual gem names not there.

**Comment by TehNut** [comment]
That can't really be solvable since I don't provide the names. I'll see if I can setup a system for it, but for now, this is the best you get.

**Comment by labpaw** [comment]
So, consider providing names for them. And why close this? You'll forget about it then.

**Comment by TehNut** [comment]
How can I provide names for an infinite number of possibilities?

**Comment by TehNut** [comment]
And on that note, how do you plan to add translations for an infinite number of possibilities?

**Comment by labpaw** [comment]
Infinite number? Are there are infinite number of ruby types? You can't give one string for all ruby from different mods? Maybe I understood something incorrectly but if it really impossible... ok.

**Comment by TehNut** [comment]
The Gem chisels are created through oreDict entries. There are theoretically an infinite number of gems.

**Comment by labpaw** [comment]
An update on this: Buildcraft Additions automatically detects dusts through oreDict (as I know) but they actually can be translated. You can check the code here: https://github.com/BCA-Team/Buildcraft-Additions/pull/296 and maybe add it into the your mod.

**Comment by TehNut** [comment]
Completed in e3a59abcb5da6133332f108acd538a90de9b0b76
