### ISSUE TITLE
Error of java.lang.NullPointerException. 

### ISSUE THREAD

**Issue by XxCoolGamesxX** [TehNut/MoreChisels#9]
I'm in the game and Pass E to go to my inventory or go to chest do error in the console.

Use: MORECHISELS-1.0-17.
Forge: 10.13.2.1291

Here Error: https://dl.dropboxusercontent.com/u/16158672/Minecraft/morechisels-error.txt

**Comment by TehNut** [comment]
Modlist?

**Comment by XxCoolGamesxX** [comment]
Modlist: https://docs.google.com/spreadsheets/d/1dOqpO_Xsya0QCMQX98yFW-VIiC5qPg08HxBBU8uA2aI/edit#gid=0

Download Modlist for test: http://www.technicpack.net/modpack/mega-planet-modpack.496164

**Comment by TehNut** [comment]
I'll look into it. I have a bad feeling it's an issue with Galacticraft.

Do you happen to have the Bedrockium Chisel in your inventory?

Unrelated note:

That spreadsheet has a few errors on it.
1. It has me listed as the developer of Chisel Facades. I am not, that would be Choonster. 
2. You link to the Chisel 2 forum post for it, when it should be [here](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2158261-chisel-facades).
3. You link to the Chisel 2 forum post for More Chisels when it should be [here](http://minecraft.curseforge.com/mc-mods/227904-morechisels).

**Comment by XxCoolGamesxX** [comment]
- Do you happen to have the Bedrockium Chisel in your inventory?

No because i just started a new world and when i press E or go to a chest the error pops up and i don't have anything in my inventory, you can also check yourself if you download my modpack to test yourself.
- Unrelated note:

Thank for update of error done in the spreadsheet. :P

**Comment by TehNut** [comment]
I downloaded your pack and was not able to recreate the issue.

**Comment by XxCoolGamesxX** [comment]
Ok :dancer:

**Comment by TehNut** [comment]
Closing until somebody can reproduce it. The method that causes the crash does not exist anymore.
